### ISSUE TITLE
How can i guide me for the Tool?

### ISSUE THREAD

**Issue by hackbert23** [mcschwa/BTCWalletMiner#11]
Hey Bro pls help me with your WalletMiner Software.
I need a good Readme for Install and using ;-)

**Comment by mcschwa** [comment]
just run it, big man

**Comment by hackbert23** [comment]
That's exactly the problem, it doesn't work, I'm having problems with the installation

**Comment by hackbert23** [comment]
can you help me pls compadre??

**Comment by mcschwa** [comment]
look, big man. I'll get you your readme. All in good and due time, currently I'm busy; if I were you get more knowledge regarding C# and get it running.

**Comment by hackbert23** [comment]
OK, it doesn't have to be anything special, just a little instruction is enough to get the tool running.  I have loaded vscode and C# and C++ and I get to the banner but then the tool stops. I apologize, I didn't mean to be intrusive, I just want to finally be able to use the tool.

**Comment by hackbert23** [comment]
Hey mate i have install but dont work right no! is it a dummy or a fake?

**Comment by hackbert23** [comment]
Hello???

**Comment by mcschwa** [comment]
if you got it running, follow the steps as said by the tool

**Comment by hackbert23** [comment]
??
